#!/usr/bin/env bash

COMMIT_MSG_FILE_PATH=$1
DEFAULT_COMMIT_MSG=$(<"$COMMIT_MSG_FILE_PATH")

CURRENT_BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

ISSUE_NUMBER=$(grep -oE '#[0-9]+' <<< "$CURRENT_BRANCH_NAME")

if [[ "$DEFAULT_COMMIT_MSG" =~ ^([Mm]erge:|[Hh]otfix:) || "$DEFAULT_COMMIT_MSG" =~ \(#[0-9]+\) ]]; then
  SUFFIX=""
else
  SUFFIX="${ISSUE_NUMBER:+($ISSUE_NUMBER)}"
fi

echo "$DEFAULT_COMMIT_MSG${SUFFIX:+ $SUFFIX}" > "$COMMIT_MSG_FILE_PATH"
